- hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  roles:
    - upgrade-all-packages
    - install-development-tools
    - install-jdk
    - install-gradle
    - install-graalvm
