- name: Check whether Gradle is installed.
  ansible.builtin.stat:
    path: /usr/local/gradle
  register: result
  tags:
    - install-gradle

- name: Download Gradle archive
  ansible.builtin.get_url:
    url: https://github.com/gradle/gradle-distributions/releases/download/v8.12.0/gradle-8.12-bin.zip
    dest: /tmp/
  when:
    - result.stat.exists == false
  tags:
    - install-gradle

- name: Unarchive Gradle archive
  ansible.builtin.unarchive:
    src: /tmp/gradle-8.12-bin.zip
    dest: /usr/local/
    owner: root
    group: root
    remote_src: true
  when:
    - result.stat.exists == false
  tags:
    - install-gradle

- name: Create symbolic link to Gradle
  ansible.builtin.file:
    src: /usr/local/gradle-8.12
    dest: /usr/local/gradle
    state: link
    owner: root
    group: root
  when:
    - result.stat.exists == false
  tags:
    - install-gradle

- name: Copy profile for Gradle command
  copy:
    src: gradle.sh
    dest: /etc/profile.d/
    owner: root
    group: root
    mode: 0644
  tags:
    - install-gradle
