- name: Check whether JDK is installed.
  ansible.builtin.stat:
    path: /usr/local/java
  register: result
  tags:
    - install-jdk

- name: Download JDK archive
  ansible.builtin.get_url:
    url: https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz
    dest: /tmp/
  when:
    - result.stat.exists == false
  tags:
    - install-jdk

- name: Unarchive JDK archive
  ansible.builtin.unarchive:
    src: "/tmp/openjdk-21.0.2_linux-x64_bin.tar.gz"
    dest: /usr/local/
    owner: root
    group: root
    remote_src: true
  when:
    - result.stat.exists == false
  tags:
    - install-jdk

- name: Create symbolic link to JDK
  ansible.builtin.file:
    src: /usr/local/jdk-21.0.2
    dest: /usr/local/java
    state: link
    owner: root
    group: root
  when:
    - result.stat.exists == false
  tags:
    - install-jdk

- name: Remove old java command
  ansible.builtin.file:
    path: /usr/bin/java
    state: absent
  tags:
    - install-jdk

